app = "synthing"
primary_region = "ewr"

[build]
  image = "lscr.io/linuxserver/syncthing:1.23.4"

[env]
  PUID = "1000"
  PGID = "1000"
  TZ = "Etc/UTC"

[[services]]
  internal_port = 22000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 22000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 22000
  protocol = "udp"
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 22000

[[services]]
  internal_port = 21027
  protocol = "udp"
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    port = 21027

[mounts]
source="synthing_config"
destination="/config"
