app = "syncthing-i6dr06"
primary_region = "ewr"

[build]
  build-target = "deploy"

[env]
  PUID = "1000"
  PGID = "1000"
  TZ = "Etc/UTC"

[[services]]
  internal_port = 22000
  protocol = "tcp"

  [[services.ports]]
    port = 22000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 22000
  protocol = "udp"

  [[services.ports]]
    port = 22000

[[services]]
  internal_port = 21027
  protocol = "udp"

  [[services.ports]]
    port = 21027

[mounts]
source="syncthing"
destination="/var/syncthing"
